# Generated by Django 6.0.2 on 2026-02-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('prof', 'prof'), ('student', 'student')], max_length=100),
        ),
    ]
