# Generated by Django 6.0.2 on 2026-02-05 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_pdf', models.FileField(upload_to='files/')),
                ('formation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formations')),
            ],
        ),
    ]
