# Generated by Django 6.0.2 on 2026-02-05 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prof_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.prof'),
        ),
    ]
